spring:
  application:
    name: blogging-app
  cache:
    type: redis
  redis:
    host: <host>
    port: <port>
  security:
    oauth2:
      client:
        registration:
          google:
            client-id : <client-id>
            client-secret : <client-secret>
  config:
    import: "aws-parameterstore:"

  datasource:
    url: <jdbc-connection-url>
    username: <username>
    password: <password>
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port : <port>
